port: "8080"

db:
    username: "elrnrjsfuzhjdc"
    host: "ec2-23-23-182-238.compute-1.amazonaws.com"
    port: "5432"
    name: "d3ivripb4vtm54"
    sslmode: "require"

db_tables:
    users_table: "friend_user"